//! Comprehensive list of standard Unicode emoji for the Emoji tab in the emote
//! picker. Each entry is `(emoji_char, descriptive_name)`.

use crust_core::emoji::twemoji_url;
use crust_core::model::EmoteCatalogEntry;

/// Build catalog entries for Unicode emoji, using Twemoji CDN URLs.
pub fn emoji_catalog_entries() -> Vec<EmoteCatalogEntry> {
    EMOJI_LIST
        .iter()
        .map(|&(ch, _name)| {
            let codepoints: Vec<u32> = ch.chars().map(|c| c as u32).collect();
            EmoteCatalogEntry {
                code: ch.to_owned(),
                provider: "emoji".to_owned(),
                url: twemoji_url(&codepoints),
                scope: "global".to_owned(),
            }
        })
        .collect()
}

/// `(emoji, name)` – ordered by category for a natural browsing experience.
pub const EMOJI_LIST: &[(&str, &str)] = &[
    // ── Smileys & Emotion ───────────────────────────────────────────────
    ("😀", "grinning face"),
    ("😃", "grinning face with big eyes"),
    ("😄", "grinning face with smiling eyes"),
    ("😁", "beaming face with smiling eyes"),
    ("😆", "grinning squinting face"),
    ("😅", "grinning face with sweat"),
    ("🤣", "rolling on the floor laughing"),
    ("😂", "face with tears of joy"),
    ("🙂", "slightly smiling face"),
    ("🙃", "upside-down face"),
    ("😉", "winking face"),
    ("😊", "smiling face with smiling eyes"),
    ("😇", "smiling face with halo"),
    ("🥰", "smiling face with hearts"),
    ("😍", "smiling face with heart-eyes"),
    ("🤩", "star-struck"),
    ("😘", "face blowing a kiss"),
    ("😗", "kissing face"),
    ("😚", "kissing face with closed eyes"),
    ("😙", "kissing face with smiling eyes"),
    ("🥲", "smiling face with tear"),
    ("😋", "face savoring food"),
    ("😛", "face with tongue"),
    ("😜", "winking face with tongue"),
    ("🤪", "zany face"),
    ("😝", "squinting face with tongue"),
    ("🤑", "money-mouth face"),
    ("🤗", "hugging face"),
    ("🤭", "face with hand over mouth"),
    ("🤫", "shushing face"),
    ("🤔", "thinking face"),
    ("🫡", "saluting face"),
    ("🤐", "zipper-mouth face"),
    ("🤨", "face with raised eyebrow"),
    ("😐", "neutral face"),
    ("😑", "expressionless face"),
    ("😶", "face without mouth"),
    ("🫥", "dotted line face"),
    ("😏", "smirking face"),
    ("😒", "unamused face"),
    ("🙄", "face with rolling eyes"),
    ("😬", "grimacing face"),
    ("🤥", "lying face"),
    ("😌", "relieved face"),
    ("😔", "pensive face"),
    ("😪", "sleepy face"),
    ("🤤", "drooling face"),
    ("😴", "sleeping face"),
    ("😷", "face with medical mask"),
    ("🤒", "face with thermometer"),
    ("🤕", "face with head-bandage"),
    ("🤢", "nauseated face"),
    ("🤮", "face vomiting"),
    ("🥵", "hot face"),
    ("🥶", "cold face"),
    ("🥴", "woozy face"),
    ("😵", "face with crossed-out eyes"),
    ("🤯", "exploding head"),
    ("🤠", "cowboy hat face"),
    ("🥳", "partying face"),
    ("🥸", "disguised face"),
    ("😎", "smiling face with sunglasses"),
    ("🤓", "nerd face"),
    ("🧐", "face with monocle"),
    ("😕", "confused face"),
    ("🫤", "face with diagonal mouth"),
    ("😟", "worried face"),
    ("🙁", "slightly frowning face"),
    ("😮", "face with open mouth"),
    ("😯", "hushed face"),
    ("😲", "astonished face"),
    ("😳", "flushed face"),
    ("🥺", "pleading face"),
    ("🥹", "face holding back tears"),
    ("😦", "frowning face with open mouth"),
    ("😧", "anguished face"),
    ("😨", "fearful face"),
    ("😰", "anxious face with sweat"),
    ("😥", "sad but relieved face"),
    ("😢", "crying face"),
    ("😭", "loudly crying face"),
    ("😱", "face screaming in fear"),
    ("😖", "confounded face"),
    ("😣", "persevering face"),
    ("😞", "disappointed face"),
    ("😓", "downcast face with sweat"),
    ("😩", "weary face"),
    ("😫", "tired face"),
    ("🥱", "yawning face"),
    ("😤", "face with steam from nose"),
    ("😡", "pouting face"),
    ("😠", "angry face"),
    ("🤬", "face with symbols on mouth"),
    ("😈", "smiling face with horns"),
    ("👿", "angry face with horns"),
    ("💀", "skull"),
    ("☠️", "skull and crossbones"),
    ("💩", "pile of poo"),
    ("🤡", "clown face"),
    ("👹", "ogre"),
    ("👺", "goblin"),
    ("👻", "ghost"),
    ("👽", "alien"),
    ("👾", "alien monster"),
    ("🤖", "robot"),
    ("😺", "grinning cat"),
    ("😸", "grinning cat with smiling eyes"),
    ("😹", "cat with tears of joy"),
    ("😻", "smiling cat with heart-eyes"),
    ("😼", "cat with wry smile"),
    ("😽", "kissing cat"),
    ("🙀", "weary cat"),
    ("😿", "crying cat"),
    ("😾", "pouting cat"),
    ("🫶", "heart hands"),
    ("🙈", "see-no-evil monkey"),
    ("🙉", "hear-no-evil monkey"),
    ("🙊", "speak-no-evil monkey"),
    ("💋", "kiss mark"),
    ("💌", "love letter"),
    ("💘", "heart with arrow"),
    ("💝", "heart with ribbon"),
    ("💖", "sparkling heart"),
    ("💗", "growing heart"),
    ("💓", "beating heart"),
    ("💞", "revolving hearts"),
    ("💕", "two hearts"),
    ("💟", "heart decoration"),
    ("❣️", "heart exclamation"),
    ("💔", "broken heart"),
    ("❤️", "red heart"),
    ("🩷", "pink heart"),
    ("🧡", "orange heart"),
    ("💛", "yellow heart"),
    ("💚", "green heart"),
    ("💙", "blue heart"),
    ("🩵", "light blue heart"),
    ("💜", "purple heart"),
    ("🤎", "brown heart"),
    ("🖤", "black heart"),
    ("🩶", "grey heart"),
    ("🤍", "white heart"),
    ("💯", "hundred points"),
    ("💢", "anger symbol"),
    ("💥", "collision"),
    ("💫", "dizzy"),
    ("💦", "sweat droplets"),
    ("💨", "dashing away"),
    ("🕳️", "hole"),
    ("💣", "bomb"),
    ("💬", "speech balloon"),
    ("💭", "thought balloon"),
    ("💤", "zzz"),

    // ── Gestures & People ────────────────────────────────────────────────
    ("👋", "waving hand"),
    ("🤚", "raised back of hand"),
    ("🖐️", "hand with fingers splayed"),
    ("✋", "raised hand"),
    ("🖖", "vulcan salute"),
    ("🫱", "rightwards hand"),
    ("🫲", "leftwards hand"),
    ("🫳", "palm down hand"),
    ("🫴", "palm up hand"),
    ("👌", "OK hand"),
    ("🤌", "pinched fingers"),
    ("🤏", "pinching hand"),
    ("✌️", "victory hand"),
    ("🤞", "crossed fingers"),
    ("🫰", "hand with index finger and thumb crossed"),
    ("🤟", "love-you gesture"),
    ("🤘", "sign of the horns"),
    ("🤙", "call me hand"),
    ("👈", "backhand index pointing left"),
    ("👉", "backhand index pointing right"),
    ("👆", "backhand index pointing up"),
    ("🖕", "middle finger"),
    ("👇", "backhand index pointing down"),
    ("☝️", "index pointing up"),
    ("🫵", "index pointing at the viewer"),
    ("👍", "thumbs up"),
    ("👎", "thumbs down"),
    ("✊", "raised fist"),
    ("👊", "oncoming fist"),
    ("🤛", "left-facing fist"),
    ("🤜", "right-facing fist"),
    ("👏", "clapping hands"),
    ("🙌", "raising hands"),
    ("🫶", "heart hands"),
    ("👐", "open hands"),
    ("🤲", "palms up together"),
    ("🤝", "handshake"),
    ("🙏", "folded hands"),
    ("✍️", "writing hand"),
    ("💅", "nail polish"),
    ("🤳", "selfie"),
    ("💪", "flexed biceps"),
    ("👀", "eyes"),
    ("👁️", "eye"),
    ("👅", "tongue"),
    ("👄", "mouth"),
    ("🫦", "biting lip"),
    ("🧠", "brain"),

    // ── Animals & Nature ─────────────────────────────────────────────────
    ("🐶", "dog face"),
    ("🐱", "cat face"),
    ("🐭", "mouse face"),
    ("🐹", "hamster"),
    ("🐰", "rabbit face"),
    ("🦊", "fox"),
    ("🐻", "bear"),
    ("🐼", "panda"),
    ("🐨", "koala"),
    ("🐯", "tiger face"),
    ("🦁", "lion"),
    ("🐮", "cow face"),
    ("🐷", "pig face"),
    ("🐸", "frog"),
    ("🐵", "monkey face"),
    ("🐔", "chicken"),
    ("🐧", "penguin"),
    ("🐦", "bird"),
    ("🐤", "baby chick"),
    ("🦆", "duck"),
    ("🦅", "eagle"),
    ("🦉", "owl"),
    ("🦇", "bat"),
    ("🐺", "wolf"),
    ("🐗", "boar"),
    ("🐴", "horse face"),
    ("🦄", "unicorn"),
    ("🐝", "honeybee"),
    ("🪱", "worm"),
    ("🐛", "bug"),
    ("🦋", "butterfly"),
    ("🐌", "snail"),
    ("🐞", "ladybug"),
    ("🐜", "ant"),
    ("🪲", "beetle"),
    ("🐢", "turtle"),
    ("🐍", "snake"),
    ("🦎", "lizard"),
    ("🐙", "octopus"),
    ("🦑", "squid"),
    ("🦐", "shrimp"),
    ("🦀", "crab"),
    ("🐡", "blowfish"),
    ("🐠", "tropical fish"),
    ("🐟", "fish"),
    ("🐬", "dolphin"),
    ("🐳", "spouting whale"),
    ("🐋", "whale"),
    ("🦈", "shark"),
    ("🐊", "crocodile"),
    ("🐅", "tiger"),
    ("🐆", "leopard"),
    ("🦓", "zebra"),
    ("🦍", "gorilla"),
    ("🦧", "orangutan"),
    ("🐘", "elephant"),
    ("🦛", "hippopotamus"),
    ("🦏", "rhinoceros"),
    ("🐪", "camel"),
    ("🐫", "two-hump camel"),
    ("🦒", "giraffe"),
    ("🦘", "kangaroo"),
    ("🐃", "water buffalo"),
    ("🐂", "ox"),
    ("🐄", "cow"),
    ("🦌", "deer"),
    ("🐎", "horse"),
    ("🐖", "pig"),
    ("🐏", "ram"),
    ("🐑", "ewe"),
    ("🦙", "llama"),
    ("🐐", "goat"),
    ("🐕", "dog"),
    ("🐩", "poodle"),
    ("🦮", "guide dog"),
    ("🐈", "cat"),
    ("🐓", "rooster"),
    ("🦃", "turkey"),
    ("🦚", "peacock"),
    ("🦜", "parrot"),
    ("🦢", "swan"),
    ("🦩", "flamingo"),
    ("🕊️", "dove"),
    ("🐇", "rabbit"),
    ("🦝", "raccoon"),
    ("🦨", "skunk"),
    ("🦡", "badger"),
    ("🦫", "beaver"),
    ("🦦", "otter"),
    ("🦥", "sloth"),
    ("🐁", "mouse"),
    ("🐀", "rat"),
    ("🐿️", "chipmunk"),
    ("🦔", "hedgehog"),
    ("🌵", "cactus"),
    ("🎄", "Christmas tree"),
    ("🌲", "evergreen tree"),
    ("🌳", "deciduous tree"),
    ("🌴", "palm tree"),
    ("🪴", "potted plant"),
    ("🌱", "seedling"),
    ("🌿", "herb"),
    ("☘️", "shamrock"),
    ("🍀", "four leaf clover"),
    ("🎍", "pine decoration"),
    ("🪹", "empty nest"),
    ("🪺", "nest with eggs"),
    ("🍃", "leaf fluttering in wind"),
    ("🍂", "fallen leaf"),
    ("🍁", "maple leaf"),
    ("🌾", "sheaf of rice"),
    ("🌺", "hibiscus"),
    ("🌻", "sunflower"),
    ("🌹", "rose"),
    ("🥀", "wilted flower"),
    ("🌷", "tulip"),
    ("🌼", "blossom"),
    ("🌸", "cherry blossom"),
    ("💐", "bouquet"),
    ("🍄", "mushroom"),
    ("🌰", "chestnut"),

    // ── Food & Drink ─────────────────────────────────────────────────────
    ("🍎", "red apple"),
    ("🍏", "green apple"),
    ("🍐", "pear"),
    ("🍊", "tangerine"),
    ("🍋", "lemon"),
    ("🍌", "banana"),
    ("🍉", "watermelon"),
    ("🍇", "grapes"),
    ("🍓", "strawberry"),
    ("🫐", "blueberries"),
    ("🍈", "melon"),
    ("🍒", "cherries"),
    ("🍑", "peach"),
    ("🥭", "mango"),
    ("🍍", "pineapple"),
    ("🥥", "coconut"),
    ("🥝", "kiwi fruit"),
    ("🍅", "tomato"),
    ("🍆", "eggplant"),
    ("🥑", "avocado"),
    ("🫛", "pea pod"),
    ("🥦", "broccoli"),
    ("🥬", "leafy green"),
    ("🥒", "cucumber"),
    ("🌶️", "hot pepper"),
    ("🫑", "bell pepper"),
    ("🌽", "ear of corn"),
    ("🥕", "carrot"),
    ("🧄", "garlic"),
    ("🧅", "onion"),
    ("🥔", "potato"),
    ("🍠", "roasted sweet potato"),
    ("🥐", "croissant"),
    ("🥯", "bagel"),
    ("🍞", "bread"),
    ("🥖", "baguette bread"),
    ("🥨", "pretzel"),
    ("🧀", "cheese wedge"),
    ("🥚", "egg"),
    ("🍳", "cooking"),
    ("🧈", "butter"),
    ("🥞", "pancakes"),
    ("🧇", "waffle"),
    ("🥓", "bacon"),
    ("🥩", "cut of meat"),
    ("🍗", "poultry leg"),
    ("🍖", "meat on bone"),
    ("🌭", "hot dog"),
    ("🍔", "hamburger"),
    ("🍟", "french fries"),
    ("🍕", "pizza"),
    ("🫓", "flatbread"),
    ("🥪", "sandwich"),
    ("🥙", "stuffed flatbread"),
    ("🧆", "falafel"),
    ("🌮", "taco"),
    ("🌯", "burrito"),
    ("🫔", "tamale"),
    ("🥗", "green salad"),
    ("🥘", "shallow pan of food"),
    ("🫕", "fondue"),
    ("🍝", "spaghetti"),
    ("🍜", "steaming bowl"),
    ("🍲", "pot of food"),
    ("🍛", "curry rice"),
    ("🍣", "sushi"),
    ("🍱", "bento box"),
    ("🥟", "dumpling"),
    ("🦪", "oyster"),
    ("🍤", "fried shrimp"),
    ("🍙", "rice ball"),
    ("🍚", "cooked rice"),
    ("🍘", "rice cracker"),
    ("🍥", "fish cake with swirl"),
    ("🥮", "moon cake"),
    ("🍡", "dango"),
    ("🥡", "takeout box"),
    ("🍦", "soft ice cream"),
    ("🍧", "shaved ice"),
    ("🍨", "ice cream"),
    ("🍩", "doughnut"),
    ("🍪", "cookie"),
    ("🎂", "birthday cake"),
    ("🍰", "shortcake"),
    ("🧁", "cupcake"),
    ("🥧", "pie"),
    ("🍫", "chocolate bar"),
    ("🍬", "candy"),
    ("🍭", "lollipop"),
    ("🍮", "custard"),
    ("🍯", "honey pot"),
    ("🍼", "baby bottle"),
    ("🥛", "glass of milk"),
    ("☕", "hot beverage"),
    ("🍵", "teacup without handle"),
    ("🍶", "sake"),
    ("🍾", "bottle with popping cork"),
    ("🍷", "wine glass"),
    ("🍸", "cocktail glass"),
    ("🍹", "tropical drink"),
    ("🍺", "beer mug"),
    ("🍻", "clinking beer mugs"),
    ("🥂", "clinking glasses"),
    ("🥃", "tumbler glass"),
    ("🫗", "pouring liquid"),
    ("🥤", "cup with straw"),
    ("🧋", "bubble tea"),
    ("🧃", "beverage box"),
    ("🧉", "mate"),
    ("🧊", "ice"),

    // ── Activities & Objects ──────────────────────────────────────────────
    ("⚽", "soccer ball"),
    ("🏀", "basketball"),
    ("🏈", "american football"),
    ("⚾", "baseball"),
    ("🥎", "softball"),
    ("🎾", "tennis"),
    ("🏐", "volleyball"),
    ("🏉", "rugby football"),
    ("🥏", "flying disc"),
    ("🎱", "pool 8 ball"),
    ("🪀", "yo-yo"),
    ("🏓", "ping pong"),
    ("🏸", "badminton"),
    ("🏒", "ice hockey"),
    ("🥅", "goal net"),
    ("⛳", "flag in hole"),
    ("🪁", "kite"),
    ("🏹", "bow and arrow"),
    ("🎣", "fishing pole"),
    ("🤿", "diving mask"),
    ("🥊", "boxing glove"),
    ("🥋", "martial arts uniform"),
    ("🎽", "running shirt"),
    ("🛹", "skateboard"),
    ("🛼", "roller skate"),
    ("🛷", "sled"),
    ("⛸️", "ice skate"),
    ("🎿", "skis"),
    ("🎯", "bullseye"),
    ("🎮", "video game"),
    ("🕹️", "joystick"),
    ("🎰", "slot machine"),
    ("🎲", "game die"),
    ("🧩", "puzzle piece"),
    ("🧸", "teddy bear"),
    ("🪄", "magic wand"),
    ("🎭", "performing arts"),
    ("🖼️", "framed picture"),
    ("🎨", "artist palette"),
    ("🧵", "thread"),
    ("🪡", "sewing needle"),
    ("🧶", "yarn"),
    ("🎼", "musical score"),
    ("🎵", "musical note"),
    ("🎶", "musical notes"),
    ("🎤", "microphone"),
    ("🎧", "headphone"),
    ("📻", "radio"),
    ("🎷", "saxophone"),
    ("🪗", "accordion"),
    ("🎸", "guitar"),
    ("🎹", "musical keyboard"),
    ("🎺", "trumpet"),
    ("🎻", "violin"),
    ("🪕", "banjo"),
    ("🥁", "drum"),
    ("🪘", "long drum"),
    ("📱", "mobile phone"),
    ("💻", "laptop"),
    ("🖥️", "desktop computer"),
    ("🖨️", "printer"),
    ("⌨️", "keyboard"),
    ("🖱️", "computer mouse"),
    ("💾", "floppy disk"),
    ("💿", "optical disk"),
    ("📀", "dvd"),
    ("🎥", "movie camera"),
    ("📷", "camera"),
    ("📸", "camera with flash"),
    ("📹", "video camera"),
    ("📺", "television"),
    ("🔍", "magnifying glass tilted left"),
    ("🔎", "magnifying glass tilted right"),
    ("💡", "light bulb"),
    ("🔦", "flashlight"),
    ("📖", "open book"),
    ("📚", "books"),
    ("📝", "memo"),
    ("✏️", "pencil"),
    ("🖊️", "pen"),
    ("📌", "pushpin"),
    ("📎", "paperclip"),
    ("✂️", "scissors"),
    ("📁", "file folder"),
    ("📂", "open file folder"),
    ("🗑️", "wastebasket"),
    ("🔒", "locked"),
    ("🔓", "unlocked"),
    ("🔑", "key"),
    ("🔨", "hammer"),
    ("🪓", "axe"),
    ("⛏️", "pick"),
    ("🔧", "wrench"),
    ("🔩", "nut and bolt"),
    ("⚙️", "gear"),
    ("🧲", "magnet"),
    ("💎", "gem stone"),
    ("🪙", "coin"),
    ("💰", "money bag"),
    ("💵", "dollar banknote"),
    ("💳", "credit card"),
    ("🏧", "ATM sign"),
    ("🎁", "wrapped gift"),
    ("🎀", "ribbon"),
    ("🎈", "balloon"),
    ("🎉", "party popper"),
    ("🎊", "confetti ball"),
    ("🎃", "jack-o-lantern"),
    ("🎆", "fireworks"),
    ("🎇", "sparkler"),
    ("✨", "sparkles"),
    ("🎋", "tanabata tree"),
    ("🎏", "carp streamer"),
    ("🎐", "wind chime"),
    ("🎑", "moon viewing ceremony"),
    ("🧧", "red envelope"),
    ("🎗️", "reminder ribbon"),
    ("🎟️", "admission tickets"),
    ("🎫", "ticket"),
    ("🏆", "trophy"),
    ("🏅", "sports medal"),
    ("🥇", "1st place medal"),
    ("🥈", "2nd place medal"),
    ("🥉", "3rd place medal"),

    // ── Travel & Places ──────────────────────────────────────────────────
    ("🌍", "globe showing Europe-Africa"),
    ("🌎", "globe showing Americas"),
    ("🌏", "globe showing Asia-Australia"),
    ("🌐", "globe with meridians"),
    ("🗺️", "world map"),
    ("🏔️", "snow-capped mountain"),
    ("⛰️", "mountain"),
    ("🌋", "volcano"),
    ("🗻", "mount fuji"),
    ("🏕️", "camping"),
    ("🏖️", "beach with umbrella"),
    ("🏜️", "desert"),
    ("🏝️", "desert island"),
    ("🏠", "house"),
    ("🏡", "house with garden"),
    ("🏢", "office building"),
    ("🏗️", "building construction"),
    ("🏭", "factory"),
    ("🏰", "castle"),
    ("🗼", "Tokyo tower"),
    ("🗽", "Statue of Liberty"),
    ("⛪", "church"),
    ("🕌", "mosque"),
    ("🛕", "hindu temple"),
    ("🕍", "synagogue"),
    ("⛩️", "shinto shrine"),
    ("🕋", "kaaba"),
    ("⛲", "fountain"),
    ("⛺", "tent"),
    ("🌁", "foggy"),
    ("🌃", "night with stars"),
    ("🏙️", "cityscape"),
    ("🌄", "sunrise over mountains"),
    ("🌅", "sunrise"),
    ("🌆", "cityscape at dusk"),
    ("🌇", "sunset"),
    ("🌉", "bridge at night"),
    ("🎠", "carousel horse"),
    ("🛝", "playground slide"),
    ("🎡", "ferris wheel"),
    ("🎢", "roller coaster"),
    ("🚂", "locomotive"),
    ("🚃", "railway car"),
    ("🚄", "high-speed train"),
    ("🚅", "bullet train"),
    ("🚆", "train"),
    ("🚇", "metro"),
    ("🚈", "light rail"),
    ("🚉", "station"),
    ("🚌", "bus"),
    ("🚎", "trolleybus"),
    ("🚐", "minibus"),
    ("🚑", "ambulance"),
    ("🚒", "fire engine"),
    ("🚓", "police car"),
    ("🚕", "taxi"),
    ("🚗", "automobile"),
    ("🚙", "sport utility vehicle"),
    ("🛻", "pickup truck"),
    ("🚚", "delivery truck"),
    ("🚛", "articulated lorry"),
    ("🏎️", "racing car"),
    ("🏍️", "motorcycle"),
    ("🛵", "motor scooter"),
    ("🚲", "bicycle"),
    ("🛴", "kick scooter"),
    ("🚏", "bus stop"),
    ("🛣️", "motorway"),
    ("🛤️", "railway track"),
    ("⛽", "fuel pump"),
    ("🚨", "police car light"),
    ("🚥", "horizontal traffic light"),
    ("🚦", "vertical traffic light"),
    ("🛑", "stop sign"),
    ("🚧", "construction"),
    ("⚓", "anchor"),
    ("🛟", "ring buoy"),
    ("⛵", "sailboat"),
    ("🚤", "speedboat"),
    ("🛳️", "passenger ship"),
    ("⛴️", "ferry"),
    ("🛥️", "motor boat"),
    ("🚢", "ship"),
    ("✈️", "airplane"),
    ("🛩️", "small airplane"),
    ("🛫", "airplane departure"),
    ("🛬", "airplane arrival"),
    ("🪂", "parachute"),
    ("💺", "seat"),
    ("🚁", "helicopter"),
    ("🚀", "rocket"),
    ("🛸", "flying saucer"),
    ("🛰️", "satellite"),
    ("🧳", "luggage"),

    // ── Weather & Sky ────────────────────────────────────────────────────
    ("🌙", "crescent moon"),
    ("🌛", "first quarter moon face"),
    ("🌜", "last quarter moon face"),
    ("🌡️", "thermometer"),
    ("☀️", "sun"),
    ("🌝", "full moon face"),
    ("🌞", "sun with face"),
    ("⭐", "star"),
    ("🌟", "glowing star"),
    ("🌠", "shooting star"),
    ("☁️", "cloud"),
    ("⛅", "sun behind cloud"),
    ("⛈️", "cloud with lightning and rain"),
    ("🌤️", "sun behind small cloud"),
    ("🌥️", "sun behind large cloud"),
    ("🌦️", "sun behind rain cloud"),
    ("🌧️", "cloud with rain"),
    ("🌨️", "cloud with snow"),
    ("🌩️", "cloud with lightning"),
    ("🌪️", "tornado"),
    ("🌫️", "fog"),
    ("🌬️", "wind face"),
    ("🌈", "rainbow"),
    ("☂️", "umbrella"),
    ("☔", "umbrella with rain drops"),
    ("⚡", "high voltage"),
    ("❄️", "snowflake"),
    ("🔥", "fire"),
    ("💧", "droplet"),
    ("🌊", "water wave"),

    // ── Symbols ──────────────────────────────────────────────────────────
    ("❤️", "red heart"),
    ("🩷", "pink heart"),
    ("🧡", "orange heart"),
    ("💛", "yellow heart"),
    ("💚", "green heart"),
    ("💙", "blue heart"),
    ("💜", "purple heart"),
    ("🖤", "black heart"),
    ("🤍", "white heart"),
    ("🤎", "brown heart"),
    ("♻️", "recycling symbol"),
    ("☮️", "peace symbol"),
    ("✝️", "latin cross"),
    ("☪️", "star and crescent"),
    ("🕉️", "om"),
    ("☯️", "yin yang"),
    ("🔯", "dotted six-pointed star"),
    ("♈", "Aries"),
    ("♉", "Taurus"),
    ("♊", "Gemini"),
    ("♋", "Cancer"),
    ("♌", "Leo"),
    ("♍", "Virgo"),
    ("♎", "Libra"),
    ("♏", "Scorpio"),
    ("♐", "Sagittarius"),
    ("♑", "Capricorn"),
    ("♒", "Aquarius"),
    ("♓", "Pisces"),
    ("⛎", "Ophiuchus"),
    ("▶️", "play button"),
    ("⏸️", "pause button"),
    ("⏹️", "stop button"),
    ("⏺️", "record button"),
    ("⏭️", "next track button"),
    ("⏮️", "last track button"),
    ("⏩", "fast-forward button"),
    ("⏪", "fast reverse button"),
    ("🔀", "shuffle tracks button"),
    ("🔁", "repeat button"),
    ("🔂", "repeat single button"),
    ("🔄", "counterclockwise arrows button"),
    ("🔼", "upwards button"),
    ("🔽", "downwards button"),
    ("⏫", "fast up button"),
    ("⏬", "fast down button"),
    ("➡️", "right arrow"),
    ("⬅️", "left arrow"),
    ("⬆️", "up arrow"),
    ("⬇️", "down arrow"),
    ("↗️", "up-right arrow"),
    ("↘️", "down-right arrow"),
    ("↙️", "down-left arrow"),
    ("↖️", "up-left arrow"),
    ("↕️", "up-down arrow"),
    ("↔️", "left-right arrow"),
    ("🔃", "clockwise vertical arrows"),
    ("ℹ️", "information"),
    ("🆎", "AB button"),
    ("🆑", "CL button"),
    ("🆒", "COOL button"),
    ("🆓", "FREE button"),
    ("🆔", "ID button"),
    ("🆕", "NEW button"),
    ("🆖", "NG button"),
    ("🆗", "OK button"),
    ("🆘", "SOS button"),
    ("🆙", "UP! button"),
    ("🆚", "VS button"),
    ("🈁", "Japanese here button"),
    ("🈶", "Japanese not free of charge button"),
    ("🈚", "Japanese free of charge button"),
    ("🈲", "Japanese prohibited button"),
    ("✅", "check mark button"),
    ("❌", "cross mark"),
    ("❎", "cross mark button"),
    ("➕", "plus"),
    ("➖", "minus"),
    ("➗", "divide"),
    ("❓", "red question mark"),
    ("❔", "white question mark"),
    ("❕", "white exclamation mark"),
    ("❗", "red exclamation mark"),
    ("‼️", "double exclamation mark"),
    ("⁉️", "exclamation question mark"),
    ("〰️", "wavy dash"),
    ("💱", "currency exchange"),
    ("💲", "heavy dollar sign"),
    ("⚕️", "medical symbol"),
    ("♾️", "infinity"),
    ("🔴", "red circle"),
    ("🟠", "orange circle"),
    ("🟡", "yellow circle"),
    ("🟢", "green circle"),
    ("🔵", "blue circle"),
    ("🟣", "purple circle"),
    ("🟤", "brown circle"),
    ("⚫", "black circle"),
    ("⚪", "white circle"),
    ("🟥", "red square"),
    ("🟧", "orange square"),
    ("🟨", "yellow square"),
    ("🟩", "green square"),
    ("🟦", "blue square"),
    ("🟪", "purple square"),
    ("⬛", "black large square"),
    ("⬜", "white large square"),
    ("🔶", "large orange diamond"),
    ("🔷", "large blue diamond"),
    ("🔸", "small orange diamond"),
    ("🔹", "small blue diamond"),
    ("🔺", "red triangle pointed up"),
    ("🔻", "red triangle pointed down"),
    ("🏁", "chequered flag"),
    ("🚩", "triangular flag"),
    ("🎌", "crossed flags"),
    ("🏴", "black flag"),
    ("🏳️", "white flag"),
    ("🏳️\u{200D}🌈", "rainbow flag"),
    ("🏴\u{200D}☠️", "pirate flag"),

    // ── Flags (popular) ─────────────────────────────────────────────────
    ("🇺🇸", "United States"),
    ("🇬🇧", "United Kingdom"),
    ("🇨🇦", "Canada"),
    ("🇦🇺", "Australia"),
    ("🇩🇪", "Germany"),
    ("🇫🇷", "France"),
    ("🇯🇵", "Japan"),
    ("🇰🇷", "South Korea"),
    ("🇧🇷", "Brazil"),
    ("🇲🇽", "Mexico"),
    ("🇮🇳", "India"),
    ("🇮🇹", "Italy"),
    ("🇪🇸", "Spain"),
    ("🇷🇺", "Russia"),
    ("🇨🇳", "China"),
    ("🇸🇪", "Sweden"),
    ("🇳🇴", "Norway"),
    ("🇵🇱", "Poland"),
    ("🇳🇱", "Netherlands"),
    ("🇹🇷", "Turkey"),
    ("🇦🇷", "Argentina"),
];
